### ISSUE TITLE
PopClip crashes when Extension Snippet has no name and ends with a space.

### ISSUE THREAD

**Issue by dofy** [pilotmoon/PopClip-Extensions#1179]
I found this bug that when I try extension snippet which include multi-language

```yaml
# popclip (crash)
name: 
  en: test
icon: T
javascript: popclip.showText('Hi~')
```

```yaml
# popclip (ok)
name: test
icon: T
javascript: popclip.showText('Hi~')
```
